### ISSUE TITLE
internals/db.go:71: cannot use db (type *gorm.DB) as type gorm.DB in return argument

### ISSUE THREAD

**Issue by dportabella** [octplane/wikiquote-parser#2]
Ok, so I've read about how to use go: https://golang.org/doc/code.html
I start from scratch:
```
$ export GOPATH=$HOME/go
$ go get github.com/octplane/wikiquote-parser/domenech
# github.com/octplane/wikiquote-parser/domenech/internals
/david/go/src/github.com/octplane/wikiquote-parser/domenech/internals/db.go:71: cannot use db (type *gorm.DB) as type gorm.DB in return argument
```
does this mean that it cannot get a connection to the database?
I don't think so, because I see at `internals/db.go` that creates and uses a temporary sqlite3 database, so this should be fine. I've tried also configuring internals/db.go to use my mysql database, but I get the same error.

is this a bug?

**Comment by octplane** [comment]
Hi, 

Thanks for you interest, I will try to fix the program so that it runs again. I have pushed a fix that corrects the compilation but I must fix other issues too...
