### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by octplane** [octplane/wikiquote-parser#3]
Domenech does not create anything valuable right now.

**Comment by dportabella** [comment]
What remains to be done? how much workload? 
I am interested in contributing to the project (I need to learn go though). Can I help?

**Comment by octplane** [comment]
Hey! I have fixed the biggest issue. You can now run the application, provided you have a an xml to feed it. 

You are welcome to have a look at it. Currently, it dumps the quotes in a CSV file.
Also all tests pass, and they are a good starting point to understand what does the script do.

**Comment by dportabella** [comment]
it works, thanks!
cool, i'll take a look at it.
